"""'created_form_2_0.001'

Revision ID: 40c7ec4039a9
Revises: e785798bbf70
Create Date: 2023-04-15 15:37:41.002940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c7ec4039a9'
down_revision = 'e785798bbf70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('form_2',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('rg_id', sa.Integer(), nullable=False),
    sa.Column('nod_id', sa.Integer(), nullable=False),
    sa.Column('pg_id', sa.Integer(), nullable=False),
    sa.Column('type_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nod_id'], ['name_of_diseases.id'], ),
    sa.ForeignKeyConstraint(['pg_id'], ['population_group.id'], ),
    sa.ForeignKeyConstraint(['rg_id'], ['territorial_unit.id'], ),
    sa.ForeignKeyConstraint(['type_value'], ['type_value.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_2')
    # ### end Alembic commands ###
