"""'created_NOD_0.002'

Revision ID: bc53a7808c3c
Revises: 40c7ec4039a9
Create Date: 2023-04-17 10:00:43.265603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc53a7808c3c'
down_revision = '40c7ec4039a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('name_of_diseases', sa.Column('krista_id', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('name_of_diseases', 'krista_id')
    # ### end Alembic commands ###
