"""'created_db_0.000'

Revision ID: e785798bbf70
Revises: 
Create Date: 2023-04-15 14:58:12.429901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e785798bbf70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=500), nullable=True),
    sa.Column('name_eng', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('name_of_diseases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('num_form', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('population_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rus_total',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=500), nullable=False),
    sa.Column('name_eng', sa.String(length=500), nullable=True),
    sa.Column('geo_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geo_category_id'], ['geo_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=500), nullable=False),
    sa.Column('name_eng', sa.String(length=500), nullable=True),
    sa.Column('short_name_ru', sa.String(length=8), nullable=True),
    sa.Column('short_name_eng', sa.String(length=10), nullable=True),
    sa.Column('rus_total_id', sa.Integer(), nullable=False),
    sa.Column('geo_category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geo_category_id'], ['geo_category.id'], ),
    sa.ForeignKeyConstraint(['rus_total_id'], ['rus_total.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('territorial_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=500), nullable=True),
    sa.Column('name_eng', sa.String(length=500), nullable=True),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('geo_category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ),
    sa.ForeignKeyConstraint(['geo_category_id'], ['geo_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_1',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('rg_id', sa.Integer(), nullable=False),
    sa.Column('nod_id', sa.Integer(), nullable=False),
    sa.Column('pg_id', sa.Integer(), nullable=False),
    sa.Column('type_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nod_id'], ['name_of_diseases.id'], ),
    sa.ForeignKeyConstraint(['pg_id'], ['population_group.id'], ),
    sa.ForeignKeyConstraint(['rg_id'], ['territorial_unit.id'], ),
    sa.ForeignKeyConstraint(['type_value'], ['type_value.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccinated_measles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('vac_measles', sa.Integer(), nullable=True),
    sa.Column('unvac_population_measles', sa.Integer(), nullable=True),
    sa.Column('vac_subjects_measles', sa.Integer(), nullable=True),
    sa.Column('rg_id', sa.Integer(), nullable=False),
    sa.Column('pg_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pg_id'], ['population_group.id'], ),
    sa.ForeignKeyConstraint(['rg_id'], ['territorial_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccinated_measles')
    op.drop_table('form_1')
    op.drop_table('territorial_unit')
    op.drop_table('districts')
    op.drop_table('rus_total')
    op.drop_table('type_value')
    op.drop_table('population_group')
    op.drop_table('name_of_diseases')
    op.drop_table('geo_category')
    # ### end Alembic commands ###
