"""0.001

Revision ID: 90253afafb63
Revises: d834b87d4feb
Create Date: 2023-04-15 13:02:27.021068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90253afafb63'
down_revision = 'd834b87d4feb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('geo_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_category',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name_ru', sa.VARCHAR(length=500), nullable=True),
    sa.Column('name_eng', sa.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
